import pygame
import os


path = 'E:\Desktop\Game Development\\'

Warrior_1_idle = [pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_000.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_001.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_002.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_003.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_004.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_005.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_006.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_007.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_008.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_009.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_010.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_011.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_012.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_013.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_014.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_015.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_016.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_017.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_018.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_019.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_020.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_021.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_022.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_023.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_024.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_025.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_026.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_027.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_028.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_1\Idle Blinking\\0_Warrior_Idle Blinking_029.png'))]


Warrior_2_idle = [pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_000.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_001.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_002.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_003.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_004.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_005.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_006.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_007.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_008.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_009.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_010.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_011.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_012.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_013.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_014.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_015.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_016.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_017.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_018.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_019.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_020.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_021.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_022.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_023.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_024.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_025.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_026.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_027.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_028.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_2\Idle Blinking\\0_Warrior_Idle Blinking_029.png'))]

Warrior_3_idle = [pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_000.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_001.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_002.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_003.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_004.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_005.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_006.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_007.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_008.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_009.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_010.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_011.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_012.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_013.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_014.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_015.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_016.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_017.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_018.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_019.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_020.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_021.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_022.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_023.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_024.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_025.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_026.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_027.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_028.png')),
pygame.image.load(os.path.join(path, 'Turn_Based_Combat\Assets\Warrior\Animations\Warrior_clothes_empty\Idle Blinking\\0_Warrior_Idle Blinking_029.png'))]